// Build step for this static site. No bundler, no dependencies.
//
// What it does, in one run:
//   1. Reads script.js + style.css and turns them into content-hashed, immutable
//      files: script.<sha8>.js and style.<sha8>.css
//   2. Rewrites the references in index.html to the fresh hashed names
//   3. Regenerates _headers so hashed assets get
//        Cache-Control: public, max-age=31536000, immutable
//      (they are addressed by content, so they can never go stale)
//      and every HTML response gets
//        Cache-Control: no-cache, must-revalidate
//      (browsers revalidate cheaply — an ETag/Last-Modified 304 roundtrip —
//      so the new page and its new hashed assets are picked up on the very next
//      load with no hard refresh).
//
// Source order matters for correctness, not deployment order: because the assets
// are content-addressed, serving old index.html + old assets and then the new
// index.html + new assets in any order always yields a consistent page.
//
// Run manually:  node build.mjs
// Or let the host run it on every deploy (vercel.json / netlify.toml).

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const hash8 = (s) => createHash('sha256').update(s).digest('hex').slice(0, 8);

const js = readFileSync(join(root, 'script.js'), 'utf8');
const css = readFileSync(join(root, 'style.css'), 'utf8');
const jsName = `script.${hash8(js)}.js`;
const cssName = `style.${hash8(css)}.css`;

// Remove hashed artifacts from previous builds so a repo/manual deploy never
// ships files it no longer references. Plain style.css/script.js are the
// sources and never match these patterns.
for (const file of readdirSync(root)) {
  const stale =
    (/^script\.[0-9a-f]{8}\.js$/.test(file) && file !== jsName) ||
    (/^style\.[0-9a-f]{8}\.css$/.test(file) && file !== cssName);
  if (stale) unlinkSync(join(root, file));
}

writeFileSync(join(root, jsName), js);
writeFileSync(join(root, cssName), css);

let html = readFileSync(join(root, 'index.html'), 'utf8');
html = html.replace('"style.css"', `"${cssName}"`);
html = html.replace('"script.js"', `"${jsName}"`);
writeFileSync(join(root, 'index.html'), html);

// Vercel _headers: patterns are matched by specificity first (exact filename >
// exact path > wildcard), so the few immutable rules below always win over the
// `/*` security block regardless of their order.
const securityHeaders = [
  `Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; media-src 'self'; img-src 'self' data:; connect-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://ipinfo.io; object-src 'none'; base-uri 'self'; form-action 'none'; frame-src 'none'; frame-ancestors 'none'; upgrade-insecure-requests`,
  `X-Frame-Options: DENY`,
  `X-Content-Type-Options: nosniff`,
  `Referrer-Policy: no-referrer`,
  `Strict-Transport-Security: max-age=31536000; includeSubDomains`,
  `Permissions-Policy: camera=(), microphone=(), geolocation=(), battery=(), interest-cohort=(), autoplay=(self), fullscreen=(self)`,
];

const headers = [
  `# Generated by build.mjs - do not edit, it is rewritten on every build.`,
  ``,
  `/${jsName}`,
  `  Cache-Control: public, max-age=31536000, immutable`,
  `/${cssName}`,
  `  Cache-Control: public, max-age=31536000, immutable`,
  ``,
  `/`,
  `  Cache-Control: no-cache, must-revalidate`,
  `/index.html`,
  `  Cache-Control: no-cache, must-revalidate`,
  ``,
  `/*`,
  ...securityHeaders.map((h) => `  ${h}`),
  ``,
].join('\n');
writeFileSync(join(root, '_headers'), headers);

console.log(`Built ${jsName} (${(js.length / 1024).toFixed(1)} kB)`);
console.log(`Built ${cssName} (${(css.length / 1024).toFixed(1)} kB)`);
console.log('index.html now references the hashed files.');
console.log('_headers regenerated: immutable hashed assets, no-cache HTML.');